### ISSUE TITLE
Refactor YAML structure to extend template string in multiline.

### ISSUE THREAD

**Issue by nampdn** [SciPhi-AI/sciphi#28]
**Is your feature request related to a problem? Please describe.**
Currently, the key of YAML treated as long string while YAML has limited 1024 bytes, it would be nice if we can refactor it into a value of string and migrate the weight into separate attribute.

**Describe the solution you'd like**
Current:
```yaml
prompt_template:
    "While studying {course_name} and delving into {course_topic}, one encounters the importance of {sub_topic}. Could you offer {context} followed by an illustration of {example_style}?": 1
```

Suggest:
```yaml
prompt_template:
  - content: >
      While studying {course_name} and delving into {course_topic},  one
      encounters the importance of {sub_topic}. Could you offer {context}
      followed by an illustration of {example_style}?
    weight: 1
  - content: Another prompt
    weight: 1
```
